### ISSUE TITLE
Attribute when no EAN 13

### ISSUE THREAD

**Issue by DavidHirsch** [finarb/PharmaScraper#16]
When   no EAN 13 info, we have both "None" (cocooncenter, lafayette) and   "0" (lasante) and "Null" (other) : can we keep only one   attribute to indicate no EAN 13 info ?
--

**Comment by finarb** [comment]
Resolved:'

db.getCollection("scrapes").updateMany({ "EAN13": 0 },{ $set: { "EAN13" : "None"}})
