### ISSUE TITLE
Attribute when no Loyalty

### ISSUE THREAD

**Issue by DavidHirsch** [finarb/PharmaScraper#17]
When   no Loyalty info, we have both "None" (pharmavie, shoppharmacie) and   "Null" (other) : can we keep only one attribute to indicate no   Loyalty info ?
--

**Comment by finarb** [comment]
Again here None is where in templates Loyaly was a requyired field but not flound. Null is when its not present in the template itself

|                           _id.L 	|       _id.Template 	|  count 	|
|--------------------------------:	|-------------------:	|-------:	|
|                                 	|     pharmanity     	| 262381 	|
|               None              	|    pharmaviewol    	|  86761 	|
|                                 	|     lafayette_2    	|  43252 	|
|                                 	|      mesoigner     	|  42088 	|
|                                 	| mesoignerwithlogin 	|  25632 	|
|                                 	|      Mesoigner     	|  21499 	|
|                                 	|       aprium       	|  20969 	|
|                                 	|     lafayette_1    	|  17748 	|
|               None              	|   pharmavielogin   	|  14412 	|
|                                 	|      boticinal     	|   4352 	|
|                                 	|     citypharma     	|   2475 	|
|                                 	|   pharmacies1001   	|   1319 	|
|               None              	|    shoppharmacie   	|   1060 	|
| Fidélité cumulée0,20€ / article 	|    cocooncenter    	|    723 	|
|                                 	|       lasante      	|    627 	|
| Fidélité cumulée0,16€ / article 	|    cocooncenter    	|    573 	|
| Fidélité cumulée0,14€ / article 	|    cocooncenter    	|    571 	|
| Fidélité cumulée0,12€ / article 	|    cocooncenter    	|    543 	|
| Fidélité cumulée0,10€ / article 	|    cocooncenter    	|    526 	|
| Fidélité cumulée0,18€ / article 	|    cocooncenter    	|    450 	|
| Fidélité cumulée0,08€ / article 	| cocooncenter       	| 429    	|
| Fidélité cumulée0,22€ / article 	| cocooncenter       	| 422    	|
| Fidélité cumulée0,15€ / article 	| cocooncenter       	| 410    	|
| Fidélité cumulée0,11€ / article 	| cocooncenter       	| 380    	|
| Fidélité cumulée0,09€ / article 	| cocooncenter       	| 377    	|
| Fidélité cumulée0,30€ / article 	| cocooncenter       	| 376    	|
| Fidélité cumulée0,28€ / article 	| cocooncenter       	| 374    	|
| Fidélité cumulée0,26€ / article 	| cocooncenter       	| 364    	|
| Fidélité cumulée0,24€ / article 	| cocooncenter       	| 364    	|
| Fidélité cumulée0,13€ / article 	| cocooncenter       	| 346    	|
| Fidélité cumulée0,06€ / article 	| cocooncenter       	| 345    	|
| Fidélité cumulée0,07€ / article 	| cocooncenter       	| 330    	|
| Fidélité cumulée0,17€ / article 	| cocooncenter       	| 324    	|
| Fidélité cumulée0,40€ / article 	| cocooncenter       	| 320    	|
| Fidélité cumulée0,36€ / article 	| cocooncenter       	| 286    	|
| Fidélité cumulée0,34€ / article 	| cocooncenter       	| 285    	|
| Fidélité cumulée0,32€ / article 	| cocooncenter       	| 279    	|
| Fidélité cumulée0,19€ / article 	| cocooncenter       	| 264    	|
| Fidélité cumulée0,25€ / article 	| cocooncenter       	| 244    	|
| Fidélité cumulée0,23€ / article 	| cocooncenter       	| 211    	|
| Fidélité cumulée0,27€ / article 	| cocooncenter       	| 207    	|
| Fidélité cumulée0,38€ / article 	| cocooncenter       	| 197    	|
| Fidélité cumulée0,60€ / article 	| cocooncenter       	| 180    	|
| Fidélité cumulée0,29€ / article 	| cocooncenter       	| 177    	|
| Fidélité cumulée0,05€ / article 	| cocooncenter       	| 171    	|
| Fidélité cumulée0,21€ / article 	| cocooncenter       	| 166    	|
| Fidélité cumulée0,50€ / article 	| cocooncenter       	| 151    	|
| Fidélité cumulée0,48€ / article 	| cocooncenter       	| 150    	|
| Fidélité cumulée0,46€ / article 	| cocooncenter       	| 127    	|
| Fidélité cumulée0,44€ / article 	| cocooncenter       	| 124    	|
| Fidélité cumulée0,33€ / article 	| cocooncenter       	| 113    	|
| Fidélité cumulée0,80€ / article 	| cocooncenter       	| 111    	|
| Fidélité cumulée0,42€ / article 	| cocooncenter       	| 109    	|
| Fidélité cumulée0,56€ / article 	| cocooncenter       	| 102    	|
| Fidélité cumulée0,04€ / article 	| cocooncenter       	| 94     	|
| Fidélité cumulée0,54€ / article 	| cocooncenter       	| 91     	|
| Fidélité cumulée0,70€ / article 	| cocooncenter       	| 89     	|
| Fidélité cumulée0,31€ / article 	| cocooncenter       	| 87     	|
| Fidélité cumulée0,52€ / article 	| cocooncenter       	| 86     	|
| Fidélité cumulée0,35€ / article 	| cocooncenter       	| 84     	|
| Fidélité cumulée0,58€ / article 	| cocooncenter       	| 77     	|
| Fidélité cumulée0,72€ / article 	| cocooncenter       	| 66     	|
| Fidélité cumulée0,64€ / article 	| cocooncenter       	| 64     	|
| Fidélité cumulée0,37€ / article 	| cocooncenter       	| 62     	|
| Fidélité cumulée1,00€ / article 	| cocooncenter       	| 62     	|
| Fidélité cumulée0,45€ / article 	| cocooncenter       	| 61     	|
| Fidélité cumulée0,66€ / article 	| cocooncenter       	| 57     	|
| Fidélité cumulée0,68€ / article 	| cocooncenter       	| 57     	|
| Fidélité cumulée0,03€ / article 	| cocooncenter       	| 52     	|
| 49 RedPoints                    	| shoppharmacie      	| 50     	|
| 99 RedPoints                    	| shoppharmacie      	| 45     	|
| 59 RedPoints                    	| shoppharmacie      	| 45     	|
| Fidélité cumulée0,43€ / article 	| cocooncenter       	| 44     	|
| Fidélité cumulée0,86€ / article 	| cocooncenter       	| 43     	|
| Fidélité cumulée0,90€ / article 	| cocooncenter       	| 42     	|
| 89 RedPoints                    	| shoppharmacie      	| 41     	|
| Fidélité cumulée0,39€ / article 	| cocooncenter       	| 39     	|
| 69 RedPoints                    	| shoppharmacie      	| 38     	|
| 54 RedPoints                    	| shoppharmacie      	| 38     	|
| Fidélité cumulée0,74€ / article 	| cocooncenter       	| 36     	|
| Fidélité cumulée0,53€ / article 	| cocooncenter       	| 35     	|
| Fidélité cumulée0,76€ / article 	| cocooncenter       	| 35     	|
| 79 RedPoints                    	| shoppharmacie      	| 35     	|
| 129 RedPoints                   	| shoppharmacie      	| 35     	|
| Fidélité cumulée0,49€ / article 	| cocooncenter       	| 34     	|
| 75 RedPoints                    	| shoppharmacie      	| 33     	|
| Fidélité cumulée1,06€ / article 	| cocooncenter       	| 33     	|
| Fidélité cumulée0,78€ / article 	| cocooncenter       	| 33     	|
| Fidélité cumulée0,92€ / article 	| cocooncenter       	| 31     	|
| 44 RedPoints                    	| shoppharmacie      	| 30     	|
| 74 RedPoints                    	| shoppharmacie      	| 29     	|
| 109 RedPoints                   	| shoppharmacie      	| 29     	|
| 39 RedPoints                    	| shoppharmacie      	| 29     	|
| 64 RedPoints                    	| shoppharmacie      	| 28     	|
| Fidélité cumulée1,20€ / article 	| cocooncenter       	| 28     	|
| 85 RedPoints                    	| shoppharmacie      	| 27     	|
| 68 RedPoints                    	| shoppharmacie      	| 27     	|
| 58 RedPoints                    	| shoppharmacie      	| 27     	|
| 36 RedPoints                    	| shoppharmacie      	| 26     	|
| Fidélité cumulée0,59€ / article 	| cocooncenter       	| 26     	|
| 34 RedPoints                    	| shoppharmacie      	| 26     	|
| 88 RedPoints                    	| shoppharmacie      	| 26     	|
| Fidélité cumulée0,96€ / article 	| cocooncenter       	| 26     	|
| Fidélité cumulée0,67€ / article 	| cocooncenter       	| 25     	|
| Fidélité cumulée0,55€ / article 	| cocooncenter       	| 25     	|
| Fidélité cumulée0,47€ / article 	| cocooncenter       	| 24     	|
| 52 RedPoints                    	| shoppharmacie      	| 24     	|
| 67 RedPoints                    	| shoppharmacie      	| 24     	|
| Fidélité cumulée0,41€ / article 	| cocooncenter       	| 24     	|
| Fidélité cumulée0,63€ / article 	| cocooncenter       	| 24     	|
| 46 RedPoints                    	| shoppharmacie      	| 24     	|
| 139 RedPoints                   	| shoppharmacie      	| 23     	|
| 35 RedPoints                    	| shoppharmacie      	| 23     	|
| 42 RedPoints                    	| shoppharmacie      	| 23     	|
| 124 RedPoints                   	| shoppharmacie      	| 22     	|
| Fidélité cumulée0,62€ / article 	| cocooncenter       	| 22     	|
| 65 RedPoints                    	| shoppharmacie      	| 22     	|
| 189 RedPoints                   	| shoppharmacie      	| 21     	|
| Fidélité cumulée0,88€ / article 	| cocooncenter       	| 21     	|
| 37 RedPoints                    	| shoppharmacie      	| 21     	|
| 43 RedPoints                    	| shoppharmacie      	| 21     	|
| 53 RedPoints                    	| shoppharmacie      	| 20     	|
| 149 RedPoints                   	| shoppharmacie      	| 20     	|
| Fidélité cumulée0,51€ / article 	| cocooncenter       	| 20     	|
| 118 RedPoints                   	| shoppharmacie      	| 20     	|
| 86 RedPoints                    	| shoppharmacie      	| 20     	|
| Fidélité cumulée0,98€ / article 	| cocooncenter       	| 20     	|
| 32 RedPoints                    	| shoppharmacie      	| 20     	|
| 47 RedPoints                    	| shoppharmacie      	| 20     	|
| 108 RedPoints                   	| shoppharmacie      	| 19     	|
| 63 RedPoints                    	| shoppharmacie      	| 19     	|
| 62 RedPoints                    	| shoppharmacie      	| 19     	|
| Fidélité cumulée1,40€ / article 	| cocooncenter       	| 19     	|
| 84 RedPoints                    	| shoppharmacie      	| 19     	|
| 29 RedPoints                    	| shoppharmacie      	| 19     	|
| 31 RedPoints                    	| shoppharmacie      	| 19     	|
| 107 RedPoints                   	| shoppharmacie      	| 19     	|
| Fidélité cumulée0,65€ / article 	| cocooncenter       	| 19     	|
| 98 RedPoints                    	| shoppharmacie      	| 18     	|
| 113 RedPoints                   	| shoppharmacie      	| 18     	|
| 66 RedPoints                    	| shoppharmacie      	| 18     	|
| Fidélité cumulée0,02€ / article 	| cocooncenter       	| 18     	|
| 38 RedPoints                    	| shoppharmacie      	| 18     	|
| 55 RedPoints                    	| shoppharmacie      	| 18     	|
| 24 RedPoints                    	| shoppharmacie      	| 18     	|
| 83 RedPoints                    	| shoppharmacie      	| 17     	|
| 92 RedPoints                    	| shoppharmacie      	| 17     	|
| Fidélité cumulée1,10€ / article 	| cocooncenter       	| 17     	|
| 179 RedPoints                   	| shoppharmacie      	| 17     	|
| 81 RedPoints                    	| shoppharmacie      	| 17     	|
| Fidélité cumulée0,69€ / article 	| cocooncenter       	| 17     	|
| Fidélité cumulée0,57€ / article 	| cocooncenter       	| 17     	|
| Fidélité cumulée1,30€ / article 	| cocooncenter       	| 17     	|
| 126 RedPoints                   	| shoppharmacie      	| 17     	|
| 51 RedPoints                    	| shoppharmacie      	| 17     	|
| Fidélité cumulée0,73€ / article 	| cocooncenter       	| 16     	|
| 82 RedPoints                    	| shoppharmacie      	| 16     	|
| 56 RedPoints                    	| shoppharmacie      	| 16     	|
| 27 RedPoints                    	| shoppharmacie      	| 16     	|
| 60 RedPoints                    	| shoppharmacie      	| 16     	|
| 87 RedPoints                    	| shoppharmacie      	| 16     	|
| 199 RedPoints                   	| shoppharmacie      	| 16     	|
| 97 RedPoints                    	| shoppharmacie      	| 16     	|
| Fidélité cumulée0,94€ / article 	| cocooncenter       	| 16     	|
| 48 RedPoints                    	| shoppharmacie      	| 16     	|
| 57 RedPoints                    	| shoppharmacie      	| 16     	|
| 159 RedPoints                   	| shoppharmacie      	| 15     	|
| Fidélité cumulée1,12€ / article 	| cocooncenter       	| 15     	|
| 128 RedPoints                   	| shoppharmacie      	| 15     	|
| 90 RedPoints                    	| shoppharmacie      	| 15     	|
| 96 RedPoints                    	| shoppharmacie      	| 15     	|
| 94 RedPoints                    	| shoppharmacie      	| 15     	|
| 111 RedPoints                   	| shoppharmacie      	| 15     	|
| 156 RedPoints                   	| shoppharmacie      	| 14     	|
| 70 RedPoints                    	| shoppharmacie      	| 14     	|
| 72 RedPoints                    	| shoppharmacie      	| 14     	|
| 78 RedPoints                    	| shoppharmacie      	| 14     	|
| 93 RedPoints                    	| shoppharmacie      	| 14     	|
| 45 RedPoints                    	| shoppharmacie      	| 14     	|
| 117 RedPoints                   	| shoppharmacie      	| 14     	|
| 135 RedPoints                   	| shoppharmacie      	| 13     	|
| 136 RedPoints                   	| shoppharmacie      	| 13     	|
| Fidélité cumulée1,70€ / article 	| cocooncenter       	| 13     	|
| 119 RedPoints                   	| shoppharmacie      	| 13     	|
| 19 RedPoints                    	| shoppharmacie      	| 13     	|
| Fidélité cumulée0,84€ / article 	| cocooncenter       	| 13     	|
| 134 RedPoints                   	| shoppharmacie      	| 13     	|
|                                 	| gpo                	| 12     	|
| 80 RedPoints                    	| shoppharmacie      	| 12     	|
| 148 RedPoints                   	| shoppharmacie      	| 12     	|
| Fidélité cumulée0,83€ / article 	| cocooncenter       	| 12     	|
| Fidélité cumulée1,16€ / article 	| cocooncenter       	| 12     	|
| 178 RedPoints                   	| shoppharmacie      	| 12     	|
| 122 RedPoints                   	| shoppharmacie      	| 12     	|
| 104 RedPoints                   	| shoppharmacie      	| 12     	|
| 121 RedPoints                   	| shoppharmacie      	| 12     	|
| 102 RedPoints                   	| shoppharmacie      	| 12     	|
| 25 RedPoints                    	| shoppharmacie      	| 11     	|
| 101 RedPoints                   	| shoppharmacie      	| 11     	|
| 194 RedPoints                   	| shoppharmacie      	| 11     	|
| 106 RedPoints                   	| shoppharmacie      	| 11     	|
| Fidélité cumulée1,80€ / article 	| cocooncenter       	| 11     	|
| 77 RedPoints                    	| shoppharmacie      	| 11     	|
| 61 RedPoints                    	| shoppharmacie      	| 11     	|
| 112 RedPoints                   	| shoppharmacie      	| 11     	|
| 142 RedPoints                   	| shoppharmacie      	| 11     	|
| 133 RedPoints                   	| shoppharmacie      	| 11     	|
| 76 RedPoints                    	| shoppharmacie      	| 10     	|
| 50 RedPoints                    	| shoppharmacie      	| 10     	|
| 30 RedPoints                    	| shoppharmacie      	| 10     	|
| 114 RedPoints                   	| shoppharmacie      	| 10     	|
| 116 RedPoints                   	| shoppharmacie      	| 10     	|
| Fidélité cumulée0,85€ / article 	| cocooncenter       	| 10     	|
| Fidélité cumulée1,08€ / article 	| cocooncenter       	| 10     	|
| Fidélité cumulée1,60€ / article 	| cocooncenter       	| 10     	|
| 105 RedPoints                   	| shoppharmacie      	| 10     	|
| 41 RedPoints                    	| shoppharmacie      	| 10     	|
| 158 RedPoints                   	| shoppharmacie      	| 10     	|
| 95 RedPoints                    	| shoppharmacie      	| 10     	|
| 169 RedPoints                   	| shoppharmacie      	| 9      	|
| 71 RedPoints                    	| shoppharmacie      	| 9      	|
| 73 RedPoints                    	| shoppharmacie      	| 9      	|
| 222 RedPoints                   	| shoppharmacie      	| 9      	|
| 115 RedPoints                   	| shoppharmacie      	| 9      	|
| 140 RedPoints                   	| shoppharmacie      	| 9      	|
| 145 RedPoints                   	| shoppharmacie      	| 9      	|
| 33 RedPoints                    	| shoppharmacie      	| 8      	|
| Fidélité cumulée0,77€ / article 	| cocooncenter       	| 8

**Comment by finarb** [comment]
Nothing to resolve here
