### ISSUE TITLE
Attribute when no Promotional claim

### ISSUE THREAD

**Issue by DavidHirsch** [finarb/PharmaScraper#18]
When   no Promotional claim info, we have both "None" (aprium, boticinal,   gpo, mesoigner) and "1" (pharmabestpraden) and "Null"   (other) : can we keep only one attribute to indicate no Promotional claim   info ?
--

**Comment by finarb** [comment]
|            Value |       _id.Template |  count |
|-----------------:|-------------------:|-------:|
|       None       | mesoignerwithlogin |  25489 |
|       None       |      mesoigner     |  41015 |
|                  |       lasante      |    627 |
|                  |     citypharma     |   2475 |
|  PRIX DEGRESSIF  |       aprium       |     47 |
|     PROMOTION    |       aprium       |    321 |
|       None       |       aprium       |  20601 |
|                  |    shoppharmacie   |   4040 |
|       None       |         gpo        |     12 |
|                  |     lafayette_1    |  17748 |
|       FALSE      |    cocooncenter    |  14471 |
|                  |     pharmanity     | 262381 |
|       None       |   pharmavielogin   |  14075 |
| Prix en baisse ! |      boticinal     |    112 |
|                  |     lafayette_2    |  43252 |
|       None       |    pharmaviewol    |  86766 |
|                  |   pharmacies1001   |   1319 |
|       None       |      boticinal     |   4240 |
|       None       |      Mesoigner     |  21499 |
|       TRUE       |  pharmabestpraden  |     15 |


None means that  that template has promotional claim as a required field but for that product its absent or cant be retieved. NULL means that promoitional claim was not a required field. True is when there is a promotional object as shown  but there is no text to retrieve while false means it couldnt be found

**Comment by DavidHirsch** [comment]
OK, thanks for explaining. I understand now the usefull distinction between None / Null / True. Not sure for FALSE : how is it different from None ?

**Comment by finarb** [comment]
False is the same as None

**Comment by finarb** [comment]
Solution:

db.getCollection("scrapes").updateMany({ "Promotional_claim": false },{ $set: { "Promotional_claim" : "None"}})
